#+title: Readme

Я начинающий Android разработчик: пишу небольшие приложения, решающие задачи для меня и окружающих меня людей.
Окончил бакалавриат СПбГУ по направлению "Программирование и информационные технологии".
Учусь в магистратуре СПбГУ.
Написал несколько проектов:
 - Android Клиент для собственного VPN сервиса
   - В активной разработке. Планирую публикацию в Google Play.
 - Практическое задание для летнего online интенсива по Android разработке от Surf
 - Телеграм бот для вызова сотрудника для скалодрома El Capitan
   - Ботом уже пользуются клиенты скалодрома
   - При написании использовал Kotlin+Coroutines+Dagger 2
 - Систему автоматического освещения растений с Andoid клиентом
 - Приложение для перенаправления уведомлений с Android устройства в Телеграм бота

 В проектах использую следующие технологии:
 - Kotlin, Android Architecture Components
 - Coroutines, State Flow
 - Room, Retrofit + Kotlinx Serialization
 - Dagger 2
 - Recycler View, View Binding
 - Jetpack Navigation, Material Components
Имел небольшой опыт работы с такими технологиями:
 - Proto DataStore
 - Notification Listener Service
 - Broadcast Receiver
 И готов изучать новые

Мне интересно разрабатывать программы, которые делают что-то одно и делают это хорошо
- Кстати, я использую Arch
